# Generated by Django 5.1.3 on 2024-11-13 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='endereco',
            old_name='cidade',
            new_name='Cidade',
        ),
        migrations.RenameField(
            model_name='endereco',
            old_name='logradouro',
            new_name='Logradouro',
        ),
        migrations.AddField(
            model_name='endereco',
            name='Client',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='client.client'),
            preserve_default=False,
        ),
    ]
